url: "https://dlshriver.com"

collections:
  artifacts:
    output: true
  publications:
    output: true

defaults:
  - scope:
      path: ""
      type: "artifacts"
    values:
      layout: "artifact"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: "files/**"
    values:
      sitemap: false

# analytics:
#   google:
#     # CHANGE THIS IF YOU USE THIS TEMPLATE!
#     tracking_id: "notrack"
#   microsoft:
#     # CHANGE THIS IF YOU USE THIS TEMPLATE!
#     tracking_id: "notrack"

plugins:
  - jekyll-sitemap

include:
  - .well-known

exclude:
  - CHANGELOG
  - CNAME
  - LICENSE
  - README
  - tmp

sass:
  style: compressed
