# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Shriver
email: davidshriver@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a first year PhD student at the University of Nebraska-Lincoln. 
  My research interests are in program analysis and testing, especially 
  analysis and testing of deep learning systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davidshriver.me" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  dlshriver
linkedin_username: dlshriver

google_analytics: UA-73081335-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  - projects
  - publications

# header_pages: ['projects.md', 'contact.md']