collections:
  artifacts:
    output: true
  publications:
    output: true

defaults:
  - scope:
      path: ""
      type: "artifacts"
    values:
      layout: "artifact"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

analytics:
  google:
    tracking_id: "G-3N6Y3DYYM0"

plugins:
  - jekyll-sitemap

exclude:
  - CHANGELOG
  - CNAME
  - LICENSE
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
